### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by imoralesgt** [ECFM-USAC/GM_Counter#1]
### Firmware
- [X] Implement stable timebase
- [X] Measure CPM using timebase
- [X] Set optimal time window for moving average CPM calculations
- [ ] ~~Debounce push-buttons using WDT in counter mode~~
- [X] Clear counter and temporarily disable PULSE_IN interrupts with push-button
- [ ] ~~Implement a discrete PID controller to regulate HV stage~~
- [X] Control LCD's LED
- [ ] ~~Control LCD's LED brightness~~
- [ ] Drive red LED [P1.1] independently form speaker output
- [ ] Implement long-push (using WDT+) on USER_BTN to enable/disable sound
- [ ] Add warning LED on [P1.7]
- [ ] Show low-battery warning on LCD when turned on
- [ ] Delay splash screen show time with TA1.0
### Hardware
- [X] Solder 32.768kHz XTAL and use it as timebase driver
- [ ] ~~Measure HV stage~~
- [X] Convert sensing stage to anode-sensing mode
- [x] Voltage regulation stage
- [x] Low-battery alarm
- [ ] [_**In progress right now**_] Implement schematic in KiCAD 
- [ ] Design PCB using KiCAD
